image: atlassian/default-image:2

pipelines:
  branches:
    production:
        - step:
            services:
              - docker
            script:
              - export IMAGE_NAME=$DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:$BITBUCKET_BRANCH

              - docker build -t $IMAGE_NAME .

              - echo "$DOCKER_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_USER --password-stdin

              - docker push $IMAGE_NAME

              - chmod +x .deploy/deploy.sh && .deploy/deploy.sh
# definitions:
#   services:
#     docker:
#       memory: 3072
